name: Build pywebdriver for debian-trixie

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build package
        uses: ./.github/build

      - name: publish artefacts
        uses: actions/upload-artifact@v4
        with:
          name: pywebdriver-debian13
          path: "pkg/*.deb"

      - name: upload to github release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "pkg/*.deb"
